creation_rules:
  - path_regex: secrets\.enc\.env
    age: >-
      age14ecr3sw0gnx5p2r29tp9zc6wkv6j3vqn0fr9z7m3lmj2za6rc39qsp4ell
      age1an0vdxnfl98ytskunh9h47zfqanqaa5k8mny0yfppcjr2nd48vrscl64gs
  - path_regex: /dev/stdin
    age: >-
      age14ecr3sw0gnx5p2r29tp9zc6wkv6j3vqn0fr9z7m3lmj2za6rc39qsp4ell
      age1an0vdxnfl98ytskunh9h47zfqanqaa5k8mny0yfppcjr2nd48vrscl64gs
